name = "wsc"
account_id = "3f847e2fadeef3e583701e8fa25657b5"
compatibility_date = "2025-03-01"
workers_dev = true

[build]
command = "npm run build"

[assets]
directory = ".svelte-kit/cloudflare"

[observability.logs]
enabled = true

[[routes]]
pattern = "wsc.theserverless.dev"
custom_domain = true
