// List of weasel words from the original blog post
export const weaselWords = [
  "many",
  "various",
  "very",
  "fairly",
  "several",
  "extremely",
  "exceedingly",
  "quite",
  "remarkably",
  "few",
  "surprisingly",
  "mostly",
  "largely",
  "huge",
  "tiny",
  "are a number",
  "is a number",
  "excellent",
  "interestingly",
  "significantly",
  "substantially",
  "clearly",
  "vast",
  "relatively",
  "completely",
];

// Additional weasel words that might be useful
export const additionalWeaselWords = [
  "virtually",
  "somewhat",
  "somehow",
  "sort of",
  "kind of",
  "rather",
  "usually",
  "basically",
  "generally",
  "pretty much",
  "arguably",
  "almost",
  "occasionally",
  "approximately",
  "nearly",
  "seemingly",
  "apparently",
  "evidently",
  "conceivably",
  "possibly",
  "probably",
  "perhaps",
  "maybe",
  "certainly",
  "definitely",
  "essentially",
  "actually",
  "literally",
  "obviously",
  // Quantitative vagueness
  "numerous",
  "countless",
  "a lot",
  "tons of",
  "a great deal",
  "a significant number",
  "a considerable amount",
  // Hedging qualifiers
  "often",
  "frequently",
  "rarely",
  "seldom",
  "sometimes",
  "normally",
  "commonly",
  "typically",
  // Emphasis without substance
  "really",
  "just",
  "simply",
  "notably",
  "importantly",
  "undoubtedly",
  "unquestionably",
  // Vague degree words
  "slightly",
  "marginally",
  "moderately",
  "mildly",
  "reasonably",
  "comparatively",
  "peculiarly",
  "strangely",
  "oddly",
  "curiously",
  // Weaseling certainty
  "supposedly",
  "allegedly",
  "purportedly",
  "ostensibly",
  "presumably",
  "theoretically",
  "hypothetically",
  "in theory",
  "in practice",
];

// Combined list of all weasel words
export const allWeaselWords = [...weaselWords, ...additionalWeaselWords];

// List of irregular verb forms (past participles) from the original blog post
export const irregularVerbs = [
  "awoken",
  "been",
  "born",
  "beat",
  "beaten",
  "become",
  "begun",
  "bent",
  "beset",
  "bet",
  "bid",
  "bidden",
  "bound",
  "bitten",
  "bled",
  "blown",
  "broken",
  "bred",
  "brought",
  "broadcast",
  "built",
  "burnt",
  "burst",
  "bought",
  "cast",
  "caught",
  "chosen",
  "clung",
  "come",
  "cost",
  "crept",
  "cut",
  "dealt",
  "dug",
  "done",
  "drawn",
  "dreamt",
  "driven",
  "drunk",
  "eaten",
  "fallen",
  "fed",
  "felt",
  "fought",
  "found",
  "fit",
  "fled",
  "flung",
  "flown",
  "forbidden",
  "forgotten",
  "foregone",
  "forgiven",
  "forsaken",
  "frozen",
  "got",
  "gotten",
  "given",
  "gone",
  "ground",
  "grown",
  "hung",
  "heard",
  "hidden",
  "hit",
  "held",
  "hurt",
  "kept",
  "knelt",
  "knit",
  "known",
  "laid",
  "led",
  "leapt",
  "learnt",
  "left",
  "lent",
  "let",
  "lain",
  "lost",
  "made",
  "meant",
  "met",
  "misspelt",
  "mistaken",
  "mown",
  "overcome",
  "overdone",
  "overtaken",
  "overthrown",
  "paid",
  "pled",
  "proven",
  "put",
  "quit",
  "read",
  "rid",
  "ridden",
  "rung",
  "risen",
  "run",
  "sawn",
  "said",
  "seen",
  "sought",
  "sold",
  "sent",
  "set",
  "sewn",
  "shaken",
  "shaven",
  "shorn",
  "shed",
  "shone",
  "shod",
  "shot",
  "shown",
  "shrunk",
  "shut",
  "sung",
  "sunk",
  "sat",
  "slept",
  "slain",
  "slid",
  "slung",
  "slit",
  "smelt",
  "smitten",
  "sown",
  "spoken",
  "sped",
  "spent",
  "spilt",
  "spoilt",
  "spun",
  "spit",
  "spat",
  "split",
  "spread",
  "sprung",
  "stood",
  "stolen",
  "stuck",
  "stung",
  "stunk",
  "stridden",
  "struck",
  "strung",
  "striven",
  "sworn",
  "swept",
  "swollen",
  "swum",
  "swung",
  "taken",
  "taught",
  "torn",
  "told",
  "thought",
  "thrown",
  "thrust",
  "trod",
  "trodden",
  "understood",
  "upheld",
  "upset",
  "woken",
  "worn",
  "woven",
  "wed",
  "wept",
  "wound",
  "won",
  "withheld",
  "withstood",
  "wrung",
  "written",
  // Additional irregular past participles
  "arisen",
  "borne",
  "begotten",
  "bereft",
  "besought",
  "clad",
  "cleft",
  "dove",
  "dwelt",
  "forecast",
  "forgone",
  "fraught",
  "gilt",
  "girt",
  "graven",
  "hewn",
  "inlaid",
  "input",
  "interwoven",
  "laden",
  "leant",
  "lit",
  "misled",
  "misgiven",
  "misunderstood",
  "misbegotten",
  "outbid",
  "outdone",
  "outgrown",
  "outrun",
  "outshone",
  "outworn",
  "overbid",
  "overborne",
  "overcast",
  "overdrawn",
  "overfed",
  "overheard",
  "overlaid",
  "overpaid",
  "overridden",
  "overrun",
  "overseen",
  "oversold",
  "overspent",
  "overthought",
  "partaken",
  "preset",
  "proofread",
  "rebuilt",
  "redone",
  "relaid",
  "remade",
  "repaid",
  "rerun",
  "resold",
  "reset",
  "retold",
  "rewritten",
  "rewound",
  "rebound",
  "rethought",
  "retaken",
  "shriven",
  "slunk",
  "snuck",
  "spelt",
  "stricken",
  "sunken",
  "undergone",
  "underpaid",
  "undersold",
  "undertaken",
  "undone",
  "unfrozen",
  "unladen",
  "unmade",
  "unsaid",
  "untold",
  "unwound",
  "upswept",
  "wrought",
];

// Auxiliary verbs used in passive voice
export const auxiliaryVerbs = [
  "am",
  "are",
  "were",
  "being",
  "is",
  "been",
  "was",
  "be",
];

// Nominalizations: nouns that could be replaced with stronger verbs
export const nominalizations: Array<{ word: string; suggestion: string }> = [
  // -tion words
  { word: "utilization", suggestion: "use" },
  { word: "implementation", suggestion: "implement" },
  { word: "optimization", suggestion: "optimize" },
  { word: "documentation", suggestion: "document" },
  { word: "authorization", suggestion: "authorize" },
  { word: "authentication", suggestion: "authenticate" },
  { word: "configuration", suggestion: "configure" },
  { word: "initialization", suggestion: "initialize" },
  { word: "modification", suggestion: "modify" },
  { word: "specification", suggestion: "specify" },
  { word: "determination", suggestion: "determine" },
  { word: "establishment", suggestion: "establish" },
  { word: "continuation", suggestion: "continue" },
  { word: "examination", suggestion: "examine" },
  { word: "investigation", suggestion: "investigate" },
  { word: "facilitation", suggestion: "facilitate" },
  { word: "notification", suggestion: "notify" },
  { word: "visualization", suggestion: "visualize" },
  { word: "demonstration", suggestion: "demonstrate" },
  { word: "transformation", suggestion: "transform" },
  { word: "simplification", suggestion: "simplify" },
  { word: "maximization", suggestion: "maximize" },
  { word: "minimization", suggestion: "minimize" },
  { word: "finalization", suggestion: "finalize" },
  { word: "prioritization", suggestion: "prioritize" },
  { word: "customization", suggestion: "customize" },
  { word: "generation", suggestion: "generate" },
  { word: "consumption", suggestion: "consume" },
  { word: "acquisition", suggestion: "acquire" },
  { word: "distribution", suggestion: "distribute" },
  { word: "accumulation", suggestion: "accumulate" },
  { word: "acceleration", suggestion: "accelerate" },
  { word: "collaboration", suggestion: "collaborate" },
  { word: "communication", suggestion: "communicate" },
  { word: "recommendation", suggestion: "recommend" },
  { word: "consideration", suggestion: "consider" },
  { word: "interpretation", suggestion: "interpret" },
  { word: "consolidation", suggestion: "consolidate" },
  { word: "validation", suggestion: "validate" },
  { word: "verification", suggestion: "verify" },
  { word: "integration", suggestion: "integrate" },
  { word: "migration", suggestion: "migrate" },
  { word: "allocation", suggestion: "allocate" },
  { word: "calculation", suggestion: "calculate" },
  { word: "delegation", suggestion: "delegate" },
  { word: "duplication", suggestion: "duplicate" },
  { word: "elimination", suggestion: "eliminate" },
  { word: "evaluation", suggestion: "evaluate" },
  { word: "formulation", suggestion: "formulate" },
  { word: "indication", suggestion: "indicate" },
  { word: "installation", suggestion: "install" },
  { word: "introduction", suggestion: "introduce" },
  { word: "manipulation", suggestion: "manipulate" },
  { word: "negotiation", suggestion: "negotiate" },
  { word: "observation", suggestion: "observe" },
  { word: "operation", suggestion: "operate" },
  { word: "preparation", suggestion: "prepare" },
  { word: "presentation", suggestion: "present" },
  { word: "preservation", suggestion: "preserve" },
  { word: "prevention", suggestion: "prevent" },
  { word: "production", suggestion: "produce" },
  { word: "protection", suggestion: "protect" },
  { word: "publication", suggestion: "publish" },
  { word: "regulation", suggestion: "regulate" },
  { word: "registration", suggestion: "register" },
  { word: "replication", suggestion: "replicate" },
  { word: "representation", suggestion: "represent" },
  { word: "resolution", suggestion: "resolve" },
  { word: "restoration", suggestion: "restore" },
  { word: "restriction", suggestion: "restrict" },
  { word: "separation", suggestion: "separate" },
  { word: "simulation", suggestion: "simulate" },
  { word: "stimulation", suggestion: "stimulate" },
  { word: "substitution", suggestion: "substitute" },
  { word: "termination", suggestion: "terminate" },
  { word: "translation", suggestion: "translate" },
  { word: "variation", suggestion: "vary" },
  { word: "violation", suggestion: "violate" },
  { word: "aggregation", suggestion: "aggregate" },
  { word: "annotation", suggestion: "annotate" },
  { word: "approximation", suggestion: "approximate" },
  { word: "centralization", suggestion: "centralize" },
  { word: "classification", suggestion: "classify" },
  { word: "compensation", suggestion: "compensate" },
  { word: "completion", suggestion: "complete" },
  { word: "compression", suggestion: "compress" },
  { word: "concatenation", suggestion: "concatenate" },
  { word: "confirmation", suggestion: "confirm" },
  { word: "connection", suggestion: "connect" },
  { word: "construction", suggestion: "construct" },
  { word: "conversion", suggestion: "convert" },
  { word: "coordination", suggestion: "coordinate" },
  { word: "creation", suggestion: "create" },
  { word: "decoration", suggestion: "decorate" },
  { word: "definition", suggestion: "define" },
  { word: "derivation", suggestion: "derive" },
  { word: "description", suggestion: "describe" },
  { word: "destruction", suggestion: "destroy" },
  { word: "detection", suggestion: "detect" },
  { word: "deviation", suggestion: "deviate" },
  { word: "differentiation", suggestion: "differentiate" },
  { word: "digitization", suggestion: "digitize" },
  { word: "escalation", suggestion: "escalate" },
  { word: "estimation", suggestion: "estimate" },
  { word: "execution", suggestion: "execute" },
  { word: "expansion", suggestion: "expand" },
  { word: "exploration", suggestion: "explore" },
  { word: "exportation", suggestion: "export" },
  { word: "extraction", suggestion: "extract" },
  { word: "fabrication", suggestion: "fabricate" },
  { word: "identification", suggestion: "identify" },
  { word: "illustration", suggestion: "illustrate" },
  { word: "importation", suggestion: "import" },
  { word: "improvisation", suggestion: "improvise" },
  { word: "incorporation", suggestion: "incorporate" },
  { word: "iteration", suggestion: "iterate" },
  { word: "justification", suggestion: "justify" },
  { word: "legalization", suggestion: "legalize" },
  { word: "modernization", suggestion: "modernize" },
  { word: "monetization", suggestion: "monetize" },
  { word: "normalization", suggestion: "normalize" },
  { word: "organization", suggestion: "organize" },
  { word: "origination", suggestion: "originate" },
  { word: "participation", suggestion: "participate" },
  { word: "personalization", suggestion: "personalize" },
  { word: "polarization", suggestion: "polarize" },
  { word: "privatization", suggestion: "privatize" },
  { word: "proliferation", suggestion: "proliferate" },
  { word: "rationalization", suggestion: "rationalize" },
  { word: "reconciliation", suggestion: "reconcile" },
  { word: "remediation", suggestion: "remediate" },
  { word: "renovation", suggestion: "renovate" },
  { word: "reorganization", suggestion: "reorganize" },
  { word: "serialization", suggestion: "serialize" },
  { word: "standardization", suggestion: "standardize" },
  { word: "synchronization", suggestion: "synchronize" },
  // British -isation/-sation spellings (mirror the AmE entries above)
  { word: "utilisation", suggestion: "use" },
  { word: "visualisation", suggestion: "visualise" },
  { word: "optimisation", suggestion: "optimise" },
  { word: "organisation", suggestion: "organise" },
  { word: "authorisation", suggestion: "authorise" },
  { word: "initialisation", suggestion: "initialise" },
  { word: "prioritisation", suggestion: "prioritise" },
  { word: "customisation", suggestion: "customise" },
  { word: "normalisation", suggestion: "normalise" },
  { word: "serialisation", suggestion: "serialise" },
  { word: "standardisation", suggestion: "standardise" },
  { word: "synchronisation", suggestion: "synchronise" },
  { word: "centralisation", suggestion: "centralise" },
  { word: "personalisation", suggestion: "personalise" },
  { word: "modernisation", suggestion: "modernise" },
  { word: "monetisation", suggestion: "monetise" },
  { word: "digitisation", suggestion: "digitise" },
  // -ment words
  { word: "improvement", suggestion: "improve" },
  { word: "development", suggestion: "develop" },
  { word: "achievement", suggestion: "achieve" },
  { word: "replacement", suggestion: "replace" },
  { word: "requirement", suggestion: "require" },
  { word: "measurement", suggestion: "measure" },
  { word: "assessment", suggestion: "assess" },
  { word: "deployment", suggestion: "deploy" },
  { word: "engagement", suggestion: "engage" },
  { word: "enhancement", suggestion: "enhance" },
  { word: "enforcement", suggestion: "enforce" },
  { word: "involvement", suggestion: "involve" },
  { word: "management", suggestion: "manage" },
  { word: "arrangement", suggestion: "arrange" },
  { word: "advancement", suggestion: "advance" },
  { word: "abandonment", suggestion: "abandon" },
  { word: "accomplishment", suggestion: "accomplish" },
  { word: "acknowledgement", suggestion: "acknowledge" },
  { word: "acknowledgment", suggestion: "acknowledge" },
  { word: "adjustment", suggestion: "adjust" },
  { word: "agreement", suggestion: "agree" },
  { word: "alignment", suggestion: "align" },
  { word: "amazement", suggestion: "amaze" },
  { word: "amusement", suggestion: "amuse" },
  { word: "announcement", suggestion: "announce" },
  { word: "attachment", suggestion: "attach" },
  { word: "attainment", suggestion: "attain" },
  { word: "bewilderment", suggestion: "bewilder" },
  { word: "commitment", suggestion: "commit" },
  { word: "containment", suggestion: "contain" },
  { word: "detachment", suggestion: "detach" },
  { word: "discouragement", suggestion: "discourage" },
  { word: "displacement", suggestion: "displace" },
  { word: "embodiment", suggestion: "embody" },
  { word: "empowerment", suggestion: "empower" },
  { word: "encouragement", suggestion: "encourage" },
  { word: "endangerment", suggestion: "endanger" },
  { word: "enrichment", suggestion: "enrich" },
  { word: "entanglement", suggestion: "entangle" },
  { word: "entertainment", suggestion: "entertain" },
  { word: "entitlement", suggestion: "entitle" },
  { word: "excitement", suggestion: "excite" },
  { word: "fulfillment", suggestion: "fulfill" },
  { word: "fulfilment", suggestion: "fulfil" },
  { word: "imprisonment", suggestion: "imprison" },
  { word: "inducement", suggestion: "induce" },
  { word: "investment", suggestion: "invest" },
  { word: "judgment", suggestion: "judge" },
  { word: "judgement", suggestion: "judge" },
  { word: "mismanagement", suggestion: "mismanage" },
  { word: "postponement", suggestion: "postpone" },
  { word: "procurement", suggestion: "procure" },
  { word: "punishment", suggestion: "punish" },
  { word: "resentment", suggestion: "resent" },
  { word: "retirement", suggestion: "retire" },
  { word: "settlement", suggestion: "settle" },
  { word: "statement", suggestion: "state" },
  { word: "treatment", suggestion: "treat" },
  // -ence/-ance words
  { word: "acceptance", suggestion: "accept" },
  { word: "allowance", suggestion: "allow" },
  { word: "appearance", suggestion: "appear" },
  { word: "assistance", suggestion: "assist" },
  { word: "avoidance", suggestion: "avoid" },
  { word: "compliance", suggestion: "comply" },
  { word: "dependence", suggestion: "depend" },
  { word: "disappearance", suggestion: "disappear" },
  { word: "disturbance", suggestion: "disturb" },
  { word: "dominance", suggestion: "dominate" },
  { word: "emergence", suggestion: "emerge" },
  { word: "endurance", suggestion: "endure" },
  { word: "existence", suggestion: "exist" },
  { word: "governance", suggestion: "govern" },
  { word: "guidance", suggestion: "guide" },
  { word: "hindrance", suggestion: "hinder" },
  { word: "inheritance", suggestion: "inherit" },
  { word: "insistence", suggestion: "insist" },
  { word: "interference", suggestion: "interfere" },
  { word: "maintenance", suggestion: "maintain" },
  { word: "occurrence", suggestion: "occur" },
  { word: "performance", suggestion: "perform" },
  { word: "persistence", suggestion: "persist" },
  { word: "preference", suggestion: "prefer" },
  { word: "prevalence", suggestion: "prevail" },
  { word: "reference", suggestion: "refer" },
  { word: "reliance", suggestion: "rely" },
  { word: "reluctance", suggestion: "hesitate" },
  { word: "remembrance", suggestion: "remember" },
  { word: "resemblance", suggestion: "resemble" },
  { word: "resistance", suggestion: "resist" },
  { word: "tolerance", suggestion: "tolerate" },
  { word: "utterance", suggestion: "utter" },
  { word: "variance", suggestion: "vary" },
];

// Hedging phrases that weaken writing
export const hedgingPhrases: string[] = [
  // Personal uncertainty
  "I think", "I believe", "I feel", "I suppose", "I guess",
  "I imagine", "I assume", "I suspect", "I reckon",
  "I would say", "I would argue", "I would suggest",
  "I would think", "I would hope", "I would expect",
  "I tend to think", "I tend to believe",
  // Impersonal hedging
  "it seems", "it appears", "it would seem", "it would appear",
  "it could be said", "it might be said", "it may be said",
  "it could be argued", "it might be argued",
  "it is possible that", "it is likely that", "it is conceivable that",
  "it is worth noting", "it should be noted", "it must be noted",
  "it is interesting to note", "it goes without saying",
  "one could argue", "one might argue", "one might say",
  "one could say", "one would think", "one would expect",
  // Qualifying phrases
  "in my opinion", "in my view", "in my experience",
  "to my knowledge", "to my mind", "to my way of thinking",
  "from my perspective", "from my point of view",
  "as far as I know", "as far as I can tell",
  "as far as I am aware", "as far as I understand",
  "if I'm not mistaken", "if I recall correctly",
  "if my memory serves", "if I may say so",
  "to some extent", "to a certain degree", "to a certain extent",
  "to a large extent", "to a greater or lesser degree",
  "in some ways", "in some respects", "in a sense", "in a way",
  "more or less", "for the most part", "by and large",
  "on the whole", "all things considered",
  // Softening phrases
  "needless to say", "it stands to reason",
  "with all due respect", "if you will",
  "so to speak", "as it were", "in a manner of speaking",
  "at the end of the day", "when all is said and done",
  "having said that", "that being said", "that said",
  "be that as it may", "for what it's worth",
  // Tentative language
  "there is a chance that", "there is a possibility that",
  "there is reason to believe", "there is some evidence",
  "the evidence suggests", "this suggests that",
  "this seems to indicate", "this appears to show",
  "this would suggest", "this might indicate",
  "this could mean", "this may imply",
  "not entirely clear", "not fully understood",
  "remains to be seen", "time will tell",
];

// Filler adverbs (no overlap with allWeaselWords)
// Excluded: actually, almost, apparently, arguably, basically, certainly,
// clearly, commonly, comparatively, completely, conceivably, curiously,
// definitely, essentially, evidently, exceedingly, extremely, fairly,
// frequently, generally, hypothetically, importantly, just, largely,
// literally, marginally, maybe, mildly, moderately, mostly, nearly,
// notably, obviously, occasionally, oddly, often, ostensibly, peculiarly,
// perhaps, possibly, presumably, probably, purportedly, quite, rarely,
// rather, really, reasonably, relatively, remarkably, seemingly, seldom,
// significantly, simply, slightly, sometimes, somewhat, strangely,
// substantially, supposedly, surprisingly, theoretically, typically,
// undoubtedly, unquestionably, usually, virtually
export const fillerAdverbs: string[] = [
  "absolutely", "accordingly", "admittedly", "altogether",
  "assuredly", "categorically", "chronically", "collectively",
  "comparably", "compellingly", "conclusively", "consequently",
  "consistently", "constantly", "continually", "critically",
  "decidedly", "demonstrably", "desperately", "disproportionately",
  "drastically", "effectively", "effortlessly", "emphatically",
  "enormously", "entirely", "especially", "excitedly",
  "exclusively", "exponentially", "extraordinarily", "faithfully",
  "fortunately", "fundamentally", "genuinely", "globally",
  "gracefully", "greatly", "hastily", "historically",
  "honestly", "hopefully", "hugely", "ideally",
  "immensely", "immediately", "impossibly", "incidentally",
  "incredibly", "independently", "indisputably", "inevitably",
  "infinitely", "inherently", "insanely", "instantly",
  "irrefutably", "ironically", "markedly", "massively",
  "materially", "measurably", "mercifully", "merely",
  "miraculously", "monumentally", "naturally", "necessarily",
  "noticeably", "objectively", "obscurely", "overwhelmingly",
  "overly", "painfully", "paradoxically", "particularly",
  "perfectly", "permanently", "personally", "plainly",
  "plausibly", "positively", "practically", "precisely",
  "predictably", "predominantly", "primarily", "principally",
  "profoundly", "progressively", "promptly", "proportionally",
  "purely", "radically", "rapidly", "regrettably",
  "reliably", "repeatedly", "reportedly",
  "respectively", "ridiculously", "routinely", "sadly",
  "seriously", "severely", "sharply", "singularly",
  "solely", "specifically", "spectacularly", "steadily",
  "strikingly", "strongly", "stubbornly", "sufficiently",
  "surely", "suspiciously", "technically", "thankfully",
  "thoroughly", "tirelessly", "totally", "tremendously",
  "truly", "unanimously", "unconditionally", "undeniably",
  "understandably", "unfortunately", "uniformly", "uniquely",
  "universally", "unnecessarily", "unreasonably", "utterly",
  "vastly", "vigorously", "wholly", "wildly",
];

// Common abbreviations that should not be treated as sentence boundaries
export const abbreviations = new Set([
  // Titles
  "mr", "mrs", "ms", "dr", "prof", "sr", "jr", "st",
  "rev", "hon", "sgt", "cpl", "pvt", "gen", "col",
  "lt", "cmdr", "adm", "capt", "maj",
  // Academic / professional
  "ph.d", "m.d", "b.a", "m.a", "b.s", "m.s", "j.d", "d.d.s",
  "esq", "cpa", "dvm",
  // Common abbreviations
  "e.g", "i.e", "etc", "vs", "approx", "dept", "est",
  "govt", "inc", "corp", "ltd", "vol", "fig",
  "a.m", "p.m", "u.s", "u.k",
  "assn", "ave", "blvd", "bldg", "ct", "dist",
  "ed", "ft", "hwy", "mt", "natl", "pkg",
  "rd", "sq", "univ", "yr",
  // Months
  "jan", "feb", "mar", "apr", "jun", "jul",
  "aug", "sep", "sept", "oct", "nov", "dec",
  // Units
  "oz", "lb", "lbs", "kg", "km", "mi", "pt", "qt", "gal",
  "min", "sec", "hr", "hrs",
  // Other
  "al", "cf", "ref", "tel", "fax", "misc", "temp",
  "org", "co", "intl",
]);

// AI-tells vocabulary: words heavily overrepresented in LLM output relative to human text.
// An entry matches its `word` plus every listed inflected `variants` form; config
// `remove` keys on `word` and drops the variants with it.
// Sources: Kobak et al. 2025 (Science Advances, "excess vocabulary" corpus study);
// Juzek & Ward 2025 (COLING, "Why Does ChatGPT 'Delve' So Much?"); Liang et al. 2024
// (Stanford, "Monitoring AI-Modified Content at Scale"); Reinhart et al. 2025 (PNAS);
// Wikipedia:Signs of AI writing (WP:AISIGNS, editor-maintained catalogue);
// GPTZero / Originality.ai vendor corpus reports.
export const aiTellsVocabulary: Array<{ word: string; variants?: string[]; reason: string }> = [
  // ── Tier 1: canonical AI verbs and metaphors (extreme overuse) ──
  { word: 'delve', variants: ['delves', 'delved', 'delving'], reason: '"delve" is the canonical AI verb — massively overrepresented in LLM text (Kobak 2025; Juzek & Ward 2025)' },
  { word: 'tapestry', variants: ['tapestries'], reason: '"tapestry" (metaphorical) is a strong AI vocabulary marker' },
  { word: 'multifaceted', reason: '"multifaceted" is heavily overrepresented in AI writing' },
  { word: 'commendable', reason: '"commendable" is a classic AI praise word (Liang 2024 reviewer study)' },
  { word: 'meticulous', variants: ['meticulously'], reason: '"meticulous(ly)" appears far more often in AI than human text (Liang 2024)' },
  { word: 'intricate', variants: ['intricacies', 'intricately'], reason: '"intricate" is disproportionately used by AI models (Liang 2024; Kobak 2025)' },
  { word: 'showcase', variants: ['showcases', 'showcased', 'showcasing'], reason: '"showcase/showcasing" is a top AI verb that persists in the newest models (Juzek 2025; Kobak 2025)' },
  { word: 'emphasize', variants: ['emphasizes', 'emphasized', 'emphasizing', 'emphasise', 'emphasises', 'emphasised', 'emphasising'], reason: '"emphasize/emphasizing" is overused by every model generation to date (Juzek 2025; Kobak 2025)' },
  { word: 'boast', variants: ['boasts', 'boasted', 'boasting'], reason: '"boasts" (meaning "has") is AI copula-avoidance (WP:AISIGNS; Juzek & Ward 2025)' },
  { word: 'indelible', reason: '"indelible" ("left an indelible mark") is an extreme AI marker in narrative prose' },
  // ── Tier 2: strong overuse ──
  { word: 'nuanced', reason: '"nuanced" is a frequent AI filler adjective' },
  { word: 'comprehensive', reason: '"comprehensive" is overused by AI as a generic intensifier' },
  { word: 'pivotal', reason: '"pivotal" is disproportionately favored by AI (Liang 2024)' },
  { word: 'holistic', reason: '"holistic" appears far more in AI text than human writing' },
  { word: 'groundbreaking', reason: '"groundbreaking" is AI hyperbole' },
  { word: 'transformative', reason: '"transformative" is a strong AI vocabulary signal' },
  { word: 'encompasses', variants: ['encompass', 'encompassing', 'encompassed'], reason: '"encompasses" is overrepresented in AI-generated text' },
  { word: 'embark', variants: ['embarks', 'embarked', 'embarking'], reason: '"embark" (especially "embark on a journey") is a known AI tell' },
  { word: 'fostering', variants: ['fosters', 'fostered'], reason: '"fostering" is used far more by AI models than human writers' },
  { word: 'spearheading', variants: ['spearheaded', 'spearheads'], reason: '"spearheading" is a classic AI action verb' },
  { word: 'underscores', variants: ['underscored', 'underscoring'], reason: '"underscores" is overused by AI for emphasis (Kobak 2025; still overused by 2026-era models)' },
  { word: 'underpins', variants: ['underpinned', 'underpinning'], reason: '"underpins" is disproportionately AI-favored' },
  { word: 'leveraging', variants: ['leverages', 'leveraged'], reason: '"leveraging" is AI-corporate jargon rarely used naturally' },
  { word: 'landscape', variants: ['landscapes'], reason: '"landscape" (metaphorical) is a known AI tell' },
  { word: 'testament', reason: '"testament" is overused by AI ("a testament to...")' },
  { word: 'noteworthy', reason: '"noteworthy" is disproportionately AI-generated (Liang 2024)' },
  { word: 'invaluable', reason: '"invaluable" is overrepresented in AI text (Liang 2024)' },
  { word: 'elevate', variants: ['elevates', 'elevating'], reason: '"elevate" is a frequent AI verb' },
  { word: 'garner', variants: ['garners', 'garnered', 'garnering'], reason: '"garner" ("garnered significant attention") is AI-favored (Juzek 2025; Kobak 2025)' },
  { word: 'vibrant', reason: '"vibrant" is AI promotional language (Reinhart PNAS 2025; WP:AISIGNS)' },
  { word: 'nestled', reason: '"nestled" is classic AI travel-guide puffery (WP:AISIGNS)' },
  { word: 'interplay', reason: '"interplay" is overrepresented in AI text (Kobak 2025)' },
  { word: 'enhance', variants: ['enhances', 'enhanced', 'enhancing'], reason: '"enhance" is overused by every model generation to date (Kobak 2025; Russell 2025)' },
  { word: 'innovative', reason: '"innovative" is a top AI praise adjective (Liang 2024)' },
  { word: 'seamless', variants: ['seamlessly'], reason: '"seamless(ly)" is AI marketing-speak (Liang 2024; vendor corpus lists)' },
  { word: 'revolutionize', variants: ['revolutionizes', 'revolutionized', 'revolutionizing', 'revolutionise', 'revolutionises', 'revolutionised', 'revolutionising'], reason: '"revolutionize" is AI hype vocabulary' },
  { word: 'cutting-edge', reason: '"cutting-edge" is AI tech-hype vocabulary' },
  { word: 'ever-evolving', reason: '"ever-evolving" is an AI cliche modifier ("ever-evolving landscape")' },
  { word: 'game-changer', variants: ['game-changing', 'game changer'], reason: '"game-changer" is AI marketing hyperbole' },
  { word: 'empower', variants: ['empowers', 'empowered', 'empowering'], reason: '"empower" is overrepresented in AI marketing prose' },
  { word: 'unleash', variants: ['unleashes', 'unleashed', 'unleashing'], reason: '"unleash" ("unleash the power of") is AI hype vocabulary' },
  { word: 'unwavering', reason: '"unwavering" ("unwavering commitment") is an AI intensifier' },
  { word: 'paramount', reason: '"paramount" is AI-formal where "most important" would do' },
  { word: 'stark', reason: '"stark" ("a stark reminder/contrast") is overrepresented in AI text (Kobak 2025)' },
  { word: 'utilize', variants: ['utilizes', 'utilized', 'utilizing', 'utilise', 'utilises', 'utilised', 'utilising'], reason: '"utilize" is stiff AI diction — humans write "use"' },
  { word: 'synergy', variants: ['synergies'], reason: '"synergy" is AI corporate-speak' },
  { word: 'poignant', reason: '"poignant" is overrepresented in AI narrative prose (Kobak 2025)' },
  { word: 'surpass', variants: ['surpasses', 'surpassed', 'surpassing'], reason: '"surpass" is AI-favored comparative language (Kobak 2025)' },
  { word: 'versatile', variants: ['versatility'], reason: '"versatile" is a top AI praise adjective (Liang 2024)' },
  // ── Tier 3: moderate overuse ──
  { word: 'robust', reason: '"robust" is AI jargon — humans rarely use it outside engineering' },
  { word: 'streamline', variants: ['streamlines', 'streamlined', 'streamlining'], reason: '"streamline" is overrepresented in AI-generated content' },
  { word: 'crucial', reason: '"crucial" is overused by AI where "important" would do (Liang 2024)' },
  { word: 'realm', variants: ['realms'], reason: '"realm" (metaphorical, "in the realm of") is AI-favored (Liang 2024)' },
  { word: 'paradigm', variants: ['paradigms'], reason: '"paradigm" is overrepresented in AI text' },
  { word: 'myriad', reason: '"myriad" is disproportionately AI-generated' },
  { word: 'plethora', reason: '"plethora" is a known AI vocabulary marker' },
  { word: 'beacon', reason: '"beacon" (metaphorical) is AI-overused ("a beacon of hope")' },
  { word: 'bustling', reason: '"bustling" is overrepresented in AI descriptions' },
  { word: 'camaraderie', reason: '"camaraderie" appears ~150x more in ChatGPT text (CMU/PNAS study)' },
  { word: 'resonate', variants: ['resonates', 'resonated', 'resonating'], reason: '"resonate" is disproportionately AI' },
  { word: 'bespoke', reason: '"bespoke" is overrepresented in AI writing' },
  { word: 'esteemed', reason: '"esteemed" is AI-formal language rarely used naturally' },
  { word: 'unparalleled', reason: '"unparalleled" is AI superlative overuse' },
  { word: 'harnessing', variants: ['harnessed'], reason: '"harnessing" (metaphorical) is AI-overused ("harnessing the power of")' },
  { word: 'adept', reason: '"adept" is disproportionately AI-generated' },
  { word: 'aligns', reason: '"aligns" / "aligns with" is AI transition overuse' },
  { word: 'burgeoning', reason: '"burgeoning" is overrepresented in AI text (Kobak 2025)' },
  { word: 'renowned', reason: '"renowned" is AI promotional puffery (WP:AISIGNS)' },
  { word: 'breathtaking', reason: '"breathtaking" is AI promotional language (WP:AISIGNS)' },
  { word: 'profound', reason: '"profound" is AI-favored gravitas (WP:AISIGNS puffery list)' },
  { word: 'enduring', reason: '"enduring" ("enduring legacy") is AI legacy-puffery (Kobak 2025; WP:AISIGNS)' },
  { word: 'bolster', variants: ['bolsters', 'bolstered', 'bolstering'], reason: '"bolster" is overrepresented in AI text (Kobak 2025)' },
  { word: 'excels', reason: '"excels" is AI praise language ("the tool excels at...")' },
  { word: 'captivate', variants: ['captivates', 'captivated', 'captivating'], reason: '"captivate/captivating" is AI narrative puffery' },
  { word: 'daunting', reason: '"daunting" is overrepresented in AI text (Kobak 2025)' },
  { word: 'demystify', variants: ['demystifies', 'demystified', 'demystifying'], reason: '"demystify" is AI blog-title vocabulary' },
  { word: 'elucidate', variants: ['elucidates', 'elucidated', 'elucidating'], reason: '"elucidate" is stiff AI-academic diction' },
  { word: 'exemplary', reason: '"exemplary" is AI praise vocabulary' },
  { word: 'exemplifies', variants: ['exemplified'], reason: '"exemplifies" is AI significance-framing (WP:AISIGNS puffery list)' },
  { word: 'kaleidoscope', reason: '"kaleidoscope" (metaphorical) is AI ornamental vocabulary' },
  { word: 'symphony', reason: '"symphony" (metaphorical, "a symphony of flavors") is AI ornamental vocabulary' },
  { word: 'linchpin', reason: '"linchpin" is overrepresented in AI analysis prose' },
  { word: 'multitude', reason: '"multitude" ("a multitude of") is AI quantity inflation' },
  { word: 'nascent', reason: '"nascent" is AI-academic diction (Kobak 2025)' },
  { word: 'uncharted', reason: '"uncharted" ("uncharted waters/territory") is an AI cliche' },
  { word: 'unveil', variants: ['unveils', 'unveiled', 'unveiling'], reason: '"unveil" is AI announcement diction (Kobak 2025)' },
  { word: 'insightful', reason: '"insightful" is a top AI praise adjective (Liang 2024)' },
  { word: 'compelling', reason: '"compelling" is AI praise vocabulary (Liang 2024)' },
  { word: 'laudable', reason: '"laudable" is AI praise vocabulary (Liang 2024 reviewer study)' },
  { word: 'ingenious', reason: '"ingenious" is AI praise vocabulary' },
  { word: 'aforementioned', reason: '"aforementioned" is stiff AI-formal backreference — humans write "this" or "that"' },
  { word: 'cognizant', reason: '"cognizant" is stiff AI-formal diction — humans write "aware"' },
  { word: 'endeavor', variants: ['endeavors', 'endeavour', 'endeavours'], reason: '"endeavor" (noun) is AI-formal where "effort" or "project" would do' },
  { word: 'facilitate', variants: ['facilitates', 'facilitated', 'facilitating'], reason: '"facilitate" is AI business-speak — humans write "help" or "enable"' },
  { word: 'skyrocket', variants: ['skyrockets', 'skyrocketed', 'skyrocketing'], reason: '"skyrocket" is AI marketing hyperbole' },
  { word: 'comprehend', reason: '"comprehend" is stiff AI diction — humans write "understand"' },
  { word: 'revitalize', variants: ['revitalizes', 'revitalized', 'revitalizing'], reason: '"revitalize" is AI marketing vocabulary' },
  { word: 'illuminates', variants: ['illuminating'], reason: '"illuminates" (figurative) is AI-academic framing' },
];

// AI-tells phrases: multi-word literal strings that are strong AI indicators.
// Matching is case-insensitive, whole-phrase (word boundaries at word-character
// edges), tolerant of curly apostrophes and flexible whitespace.
// Deliberately NOT duplicated here: phrases the hedging detector already flags
// ("at the end of the day", "it should be noted", "time will tell", "that being
// said", "needless to say") — one span, one flag.
export const aiTellsPhrases: Array<{ phrase: string; reason: string }> = [
  // Chatbot artifacts — assistant text pasted straight into prose (near-zero false-positive rate)
  { phrase: 'as an ai language model', reason: 'Chatbot self-disclosure left in pasted output' },
  { phrase: 'as a large language model', reason: 'Chatbot self-disclosure left in pasted output' },
  { phrase: 'as of my last knowledge update', reason: 'Knowledge-cutoff disclaimer left in pasted output (WP:AISIGNS)' },
  { phrase: 'my knowledge cutoff', reason: 'Knowledge-cutoff disclaimer left in pasted output' },
  { phrase: 'my training data', reason: 'Chatbot self-reference left in pasted output' },
  { phrase: "i don't have access to real-time", reason: 'Chatbot capability disclaimer left in pasted output' },
  { phrase: 'in the provided search results', reason: 'RAG-chatbot source disclaimer left in pasted output (WP:AISIGNS)' },
  { phrase: 'while specific details are limited', reason: 'RAG-chatbot hedge for missing sources (WP:AISIGNS)' },
  { phrase: 'regenerate response', reason: 'Chat-UI button label copied along with the answer' },
  { phrase: 'i hope this helps', reason: 'Assistant sign-off left in pasted output' },
  { phrase: 'i hope this message finds you well', reason: 'AI form-letter opener (WP:AISIGNS)' },
  { phrase: 'would you like me to', reason: 'Assistant follow-up offer left in pasted output' },
  { phrase: 'is there anything else i can', reason: 'Assistant closing offer left in pasted output' },
  { phrase: "let me know if you'd like", reason: 'Assistant follow-up offer left in pasted output' },
  { phrase: 'feel free to customize', reason: 'Assistant template handoff left in pasted output' },
  { phrase: 'feel free to personalize', reason: 'Assistant template handoff left in pasted output' },
  { phrase: "you're absolutely right", reason: 'Chatbot sycophancy artifact (2025-era models)' },
  // Sycophantic / conversational openers
  { phrase: 'great question', reason: 'Sycophantic AI opener — humans rarely say this in writing' },
  { phrase: 'excellent question', reason: 'Sycophantic AI opener' },
  { phrase: 'glad you asked', reason: 'AI conversational filler' },
  // Hedging preambles
  { phrase: "it's important to note that", reason: 'AI hedging preamble — add the point directly' },
  { phrase: "it's worth noting that", reason: 'AI hedging filler' },
  { phrase: "it's worth mentioning that", reason: 'AI hedging filler — just mention it' },
  { phrase: 'it is essential to', reason: 'AI importance-framing — say why, or drop it' },
  { phrase: "it's essential to", reason: 'AI importance-framing — say why, or drop it' },
  { phrase: 'it is evident that', reason: 'AI-academic hedge — show the evidence instead' },
  // Filler openers
  { phrase: "in today's fast-paced world", reason: 'AI cliche opener — 107x more in AI text than human' },
  { phrase: "in today's digital age", reason: 'AI cliche opener' },
  { phrase: "in today's rapidly evolving", reason: 'AI cliche opener variant' },
  { phrase: "in today's world", reason: 'AI scene-setting cliche opener' },
  { phrase: 'in the realm of', reason: 'AI filler phrase — 50x overrepresentation' },
  { phrase: 'in an era of', reason: 'AI scene-setting cliche' },
  { phrase: 'at its core', reason: 'AI emphasis filler — often adds nothing' },
  { phrase: 'when it comes to', reason: 'AI transition filler — overused as topic introducer' },
  { phrase: 'first and foremost', reason: 'AI list-opener filler — "first" alone works' },
  // Overly formal transitions and closers
  { phrase: 'furthermore,', reason: 'AI transition — "also" or "and" is more natural' },
  { phrase: 'moreover,', reason: 'AI transition overuse' },
  { phrase: 'additionally,', reason: 'AI transition overuse — "also" is more natural' },
  { phrase: 'in conclusion,', reason: 'AI structural cliche — rarely needed' },
  { phrase: 'in summary,', reason: 'AI wrap-up formula (WP:AISIGNS section summaries)' },
  { phrase: 'to summarize,', reason: 'AI wrap-up formula' },
  { phrase: 'in essence,', reason: 'AI restatement filler' },
  { phrase: 'key takeaway', reason: 'AI summary-listicle framing' },
  // "Let's" constructions
  { phrase: "let's dive in", reason: 'AI conversational filler' },
  { phrase: "let's explore", reason: 'AI conversational filler — just explore it' },
  { phrase: "let's delve", reason: 'AI filler combining two tells' },
  { phrase: "let's break this down", reason: 'AI structural filler' },
  { phrase: 'without further ado', reason: 'AI filler phrase before getting to the point' },
  { phrase: "here's the kicker", reason: 'AI faux-candor pivot (2024+ chatty register)' },
  // Superlative / emphasis / significance-framing
  { phrase: 'a testament to', reason: 'AI emphasis cliche' },
  { phrase: "it's not just about", reason: 'AI negation-pivot opener' },
  { phrase: 'cannot be overstated', reason: 'AI importance inflation ("the importance of X cannot be overstated")' },
  { phrase: 'highlights the importance of', reason: 'AI significance-framing formula (Juzek 2026 cross-lingual study)' },
  { phrase: 'underscores the importance of', reason: 'AI significance-framing formula' },
  { phrase: 'sheds light on', reason: 'AI-academic illumination cliche' },
  { phrase: 'gain a deeper understanding', reason: 'AI-academic filler — what specifically is understood?' },
  { phrase: 'opens new avenues', reason: 'AI-academic outlook cliche (Kobak 2025 excess phrase)' },
  { phrase: 'aims to explore', reason: 'AI meta-announcement — ~50x more frequent in AI text (GPTZero)' },
  { phrase: 'valuable insights', reason: 'AI insight-inflation collocation (WP:AISIGNS; Geng & Trotta 2025)' },
  { phrase: 'actionable insights', reason: 'AI business-speak collocation' },
  { phrase: 'rich tapestry', reason: 'AI ornamental metaphor' },
  { phrase: 'rich cultural heritage', reason: 'AI travel-brochure puffery (WP:AISIGNS)' },
  { phrase: 'treasure trove', reason: 'AI ornamental metaphor' },
  { phrase: 'hidden gem', reason: 'AI travel-listicle cliche' },
  { phrase: 'faces several challenges', reason: 'AI challenges-formula prose (WP:AISIGNS)' },
  { phrase: 'faced numerous challenges', reason: 'AI challenges-formula prose (WP:AISIGNS)' },
  { phrase: 'no discussion would be complete without', reason: 'AI completeness-formula filler' },
  // Marketing hype
  { phrase: 'unlock the potential', reason: 'AI marketing cliche' },
  { phrase: 'unlock the full potential', reason: 'AI marketing cliche' },
  { phrase: 'unlock the power', reason: 'AI marketing cliche' },
  { phrase: 'harness the power', reason: 'AI marketing cliche' },
  { phrase: 'to the next level', reason: 'AI marketing cliche ("take X to the next level")' },
  { phrase: 'to new heights', reason: 'AI marketing cliche' },
  { phrase: 'push the boundaries of', reason: 'AI marketing cliche' },
  { phrase: 'look no further', reason: 'AI sales-copy cliche' },
  { phrase: 'supercharge your', reason: 'AI marketing hype' },
  { phrase: 'secret sauce', reason: 'AI business-blog cliche' },
  { phrase: 'deep dive', reason: 'AI content-marketing cliche' },
  // Wrap-up phrases
  { phrase: 'embrace the', reason: 'AI call-to-action cliche ("embrace the future")' },
  { phrase: 'navigate the complexities', reason: 'AI closing cliche' },
  { phrase: 'navigating the complexities', reason: 'AI closing cliche' },
  { phrase: 'pave the way for', reason: 'AI forward-looking cliche' },
  { phrase: 'the possibilities are endless', reason: 'AI optimism cliche' },
];

// AI-tells structural patterns: sentence constructions (not fixed strings) that are
// documented LLM habits. Each entry is a JavaScript regex source compiled with the
// 'gi' flags. Disable individual patterns via `detectors.aiTells.removePatterns`
// (matched by name). Regexes use bounded quantifiers — no catastrophic backtracking.
// Consciously excluded as too false-positive-prone for per-instance flagging:
// em-dash density, rule-of-three triads, bold-lead bullets, title-case headings
// (all are document-level density signals, not single-span issues).
export const aiTellsPatterns: Array<{ name: string; pattern: string; reason: string }> = [
  {
    name: 'negative-parallelism',
    pattern: "\\bn(?:ot|[''’]t) (?:just|only|merely|simply|about) [^.!?\\n]{1,80}?[,;.:—–-] ?(?:it[''’]s|it is|this is|that[''’]s|they[''’]re|but rather)\\b|\\b(?:it|this|that)(?:[''’]s| is) not (?:a|an|the) [^.!?\\n]{1,60}?[.;,—–] ?(?:it|this|that)(?:[''’]s| is) (?:a|an|the)\\b",
    reason: '"It\'s not just X — it\'s Y" negative parallelism is a signature LLM construction (WP:AISIGNS; Kriss/NYT 2025)',
  },
  {
    name: 'not-only-but-also',
    pattern: '\\bnot only\\b[^.!?\\n]{2,80}?\\bbut also\\b',
    reason: '"not only... but also" is heavily overused by LLMs of every generation (Russell 2025; WP:AISIGNS)',
  },
  {
    name: 'trailing-participial-analysis',
    pattern: ',\\s+(?:further |thereby |ultimately )?(?:highlighting|underscoring|showcasing|reflecting|emphasi[sz]ing|demonstrating|signall?ing|illustrating|cementing|solidifying|reinforcing|exemplifying|epitomizing|symbolizing|embodying|heralding)\\b',
    reason: 'Trailing ", highlighting/underscoring/showcasing..." significance clauses are the best-evidenced syntactic AI tell (Reinhart PNAS 2025; WP:AISIGNS)',
  },
  {
    name: 'vague-attribution',
    pattern: '\\b(?:experts|critics|observers|scholars|analysts|commentators|industry (?:reports|experts|leaders|insiders)) (?:have )?(?:widely )?(?:argued?s?|agreed?s?|suggests?|suggested|believed?s?|noted?s?|cited?s?|claims?|claimed|warns?|warned|say|pointed? out)\\b|\\bstudies (?:show|suggest|indicate|have shown)\\b|\\bresearch (?:shows|suggests|indicates|has shown)\\b',
    reason: 'Vague authority attribution ("experts agree", "studies show") without a named source is a documented AI weasel pattern (WP:AISIGNS)',
  },
  {
    name: 'audience-hedge',
    pattern: "\\bwhether you[''’]re (?:a|an|new|just|looking|building|running)\\b[^.!?\\n]{1,80}?\\bor\\b",
    reason: '"Whether you\'re a X or a Y" audience-flattening openers are an AI content-marketing formula',
  },
  {
    name: 'despite-challenges',
    pattern: '\\bdespite (?:its|these|their|the)\\b[^.!?\\n]{1,60}?\\b(?:faces?|faced|continues? to face|remains?)\\b[^.!?\\n]{0,40}?\\bchallenges\\b',
    reason: 'The "Despite its X, [subject] faces challenges" formula is a documented AI outline habit (WP:AISIGNS; Russell 2025)',
  },
  {
    name: 'copula-puffery',
    pattern: '\\bstands as an?\\b|\\bholds the distinction of\\b|\\bserves as a (?:testament|beacon|reminder|symbol|cornerstone)\\b',
    reason: 'Inflated copulas ("stands as a", "serves as a testament") replace plain "is" in AI prose (WP:AISIGNS; Geng & Trotta 2025)',
  },
  {
    name: 'pivotal-role-claim',
    pattern: '\\bplay(?:s|ed|ing)? an? (?:crucial|pivotal|vital|key|critical|essential|significant|central|integral|major|prominent|important) (?:role|part)\\b',
    reason: '"plays a crucial/vital/key role" is an AI significance cliche (WP:AISIGNS grandiose-phrase list)',
  },
  {
    name: 'false-range',
    pattern: '\\bfrom [^,.;!?\\n]{2,40} to [^,.;!?\\n]{2,40}, (?:and )?from [^,.;!?\\n]{2,40} to\\b',
    reason: 'Chained "from X to Y, from Z to W" false ranges are a documented AI comprehensiveness gesture (WP:AISIGNS)',
  },
  {
    name: 'unfilled-placeholder',
    pattern: "\\[(?:your (?:name|username|email|company(?: name)?)|company name|insert [^\\]\\n]{2,40}|[a-z ]{0,20}goes here)\\]",
    reason: 'Unfilled template placeholders ("[Your Name]", "[insert X]") are AI draft output left incomplete (WP:AISIGNS)',
  },
  {
    name: 'meta-announcement',
    pattern: '\\bthis (?:article|blog post|post|essay|guide) (?:aims|seeks) to\\b',
    reason: '"This article aims to explore..." meta-announcements are ~50x more frequent in AI text (GPTZero)',
  },
  {
    name: 'dance-metaphor',
    pattern: '\\b(?:intricate|delicate|complex|careful) dance\\b',
    reason: 'The "delicate dance between X and Y" metaphor is a documented LLM favorite',
  },
];
