// List of weasel words from the original blog post
export const weaselWords = [
  "many",
  "various",
  "very",
  "fairly",
  "several",
  "extremely",
  "exceedingly",
  "quite",
  "remarkably",
  "few",
  "surprisingly",
  "mostly",
  "largely",
  "huge",
  "tiny",
  "are a number",
  "is a number",
  "excellent",
  "interestingly",
  "significantly",
  "substantially",
  "clearly",
  "vast",
  "relatively",
  "completely",
];

// Additional weasel words that might be useful
export const additionalWeaselWords = [
  "virtually",
  "somewhat",
  "somehow",
  "sort of",
  "kind of",
  "rather",
  "usually",
  "basically",
  "generally",
  "pretty much",
  "arguably",
  "almost",
  "occasionally",
  "approximately",
  "nearly",
  "seemingly",
  "apparently",
  "evidently",
  "conceivably",
  "possibly",
  "probably",
  "perhaps",
  "maybe",
  "certainly",
  "definitely",
  "essentially",
  "actually",
  "literally",
  "obviously",
  // Quantitative vagueness
  "numerous",
  "countless",
  "a lot",
  "tons of",
  "a great deal",
  "a significant number",
  "a considerable amount",
  // Hedging qualifiers
  "often",
  "frequently",
  "rarely",
  "seldom",
  "sometimes",
  "normally",
  "commonly",
  "typically",
  // Emphasis without substance
  "really",
  "just",
  "simply",
  "notably",
  "importantly",
  "undoubtedly",
  "unquestionably",
  // Vague degree words
  "slightly",
  "marginally",
  "moderately",
  "mildly",
  "reasonably",
  "comparatively",
  "peculiarly",
  "strangely",
  "oddly",
  "curiously",
  // Weaseling certainty
  "supposedly",
  "allegedly",
  "purportedly",
  "ostensibly",
  "presumably",
  "theoretically",
  "hypothetically",
  "in theory",
  "in practice",
];

// Combined list of all weasel words
export const allWeaselWords = [...weaselWords, ...additionalWeaselWords];

// List of irregular verb forms (past participles) from the original blog post
export const irregularVerbs = [
  "awoken",
  "been",
  "born",
  "beat",
  "become",
  "begun",
  "bent",
  "beset",
  "bet",
  "bid",
  "bidden",
  "bound",
  "bitten",
  "bled",
  "blown",
  "broken",
  "bred",
  "brought",
  "broadcast",
  "built",
  "burnt",
  "burst",
  "bought",
  "cast",
  "caught",
  "chosen",
  "clung",
  "come",
  "cost",
  "crept",
  "cut",
  "dealt",
  "dug",
  "dived",
  "done",
  "drawn",
  "dreamt",
  "driven",
  "drunk",
  "eaten",
  "fallen",
  "fed",
  "felt",
  "fought",
  "found",
  "fit",
  "fled",
  "flung",
  "flown",
  "forbidden",
  "forgotten",
  "foregone",
  "forgiven",
  "forsaken",
  "frozen",
  "gotten",
  "given",
  "gone",
  "ground",
  "grown",
  "hung",
  "heard",
  "hidden",
  "hit",
  "held",
  "hurt",
  "kept",
  "knelt",
  "knit",
  "known",
  "laid",
  "led",
  "leapt",
  "learnt",
  "left",
  "lent",
  "let",
  "lain",
  "lighted",
  "lost",
  "made",
  "meant",
  "met",
  "misspelt",
  "mistaken",
  "mown",
  "overcome",
  "overdone",
  "overtaken",
  "overthrown",
  "paid",
  "pled",
  "proven",
  "put",
  "quit",
  "read",
  "rid",
  "ridden",
  "rung",
  "risen",
  "run",
  "sawn",
  "said",
  "seen",
  "sought",
  "sold",
  "sent",
  "set",
  "sewn",
  "shaken",
  "shaven",
  "shorn",
  "shed",
  "shone",
  "shod",
  "shot",
  "shown",
  "shrunk",
  "shut",
  "sung",
  "sunk",
  "sat",
  "slept",
  "slain",
  "slid",
  "slung",
  "slit",
  "smitten",
  "sown",
  "spoken",
  "sped",
  "spent",
  "spilt",
  "spun",
  "spit",
  "split",
  "spread",
  "sprung",
  "stood",
  "stolen",
  "stuck",
  "stung",
  "stunk",
  "stridden",
  "struck",
  "strung",
  "striven",
  "sworn",
  "swept",
  "swollen",
  "swum",
  "swung",
  "taken",
  "taught",
  "torn",
  "told",
  "thought",
  "thrived",
  "thrown",
  "thrust",
  "trodden",
  "understood",
  "upheld",
  "upset",
  "woken",
  "worn",
  "woven",
  "wed",
  "wept",
  "wound",
  "won",
  "withheld",
  "withstood",
  "wrung",
  "written",
  // Additional irregular past participles
  "arisen",
  "borne",
  "begotten",
  "bereft",
  "besought",
  "bowed",
  "clad",
  "cleft",
  "dove",
  "dreamed",
  "dwelt",
  "forbade",
  "forecast",
  "forgone",
  "forsook",
  "fraught",
  "gilt",
  "girt",
  "graven",
  "hewn",
  "inlaid",
  "input",
  "interwoven",
  "laden",
  "leant",
  "lit",
  "misled",
  "misgiven",
  "misunderstood",
  "misbegotten",
  "outbid",
  "outdone",
  "outgrown",
  "outrun",
  "outshone",
  "outworn",
  "overbid",
  "overborne",
  "overcast",
  "overdrawn",
  "overfed",
  "overheard",
  "overlaid",
  "overpaid",
  "overridden",
  "overrun",
  "overseen",
  "oversold",
  "overspent",
  "overthought",
  "partaken",
  "preset",
  "proofread",
  "rebuilt",
  "redone",
  "relaid",
  "remade",
  "repaid",
  "rerun",
  "resold",
  "reset",
  "retold",
  "rewritten",
  "rewound",
  "rebound",
  "rethought",
  "retaken",
  "shriven",
  "slunk",
  "snuck",
  "spelt",
  "stricken",
  "sunken",
  "swapped",
  "undergone",
  "underpaid",
  "undersold",
  "undertaken",
  "undone",
  "unfrozen",
  "unladen",
  "unmade",
  "unsaid",
  "untold",
  "unwound",
  "upswept",
  "wrought",
];

// Auxiliary verbs used in passive voice
export const auxiliaryVerbs = [
  "am",
  "are",
  "were",
  "being",
  "is",
  "been",
  "was",
  "be",
];

// Nominalizations: nouns that could be replaced with stronger verbs
export const nominalizations: Array<{ word: string; suggestion: string }> = [
  // -tion words
  { word: "utilization", suggestion: "use" },
  { word: "implementation", suggestion: "implement" },
  { word: "optimization", suggestion: "optimize" },
  { word: "documentation", suggestion: "document" },
  { word: "authorization", suggestion: "authorize" },
  { word: "authentication", suggestion: "authenticate" },
  { word: "configuration", suggestion: "configure" },
  { word: "initialization", suggestion: "initialize" },
  { word: "modification", suggestion: "modify" },
  { word: "specification", suggestion: "specify" },
  { word: "determination", suggestion: "determine" },
  { word: "establishment", suggestion: "establish" },
  { word: "continuation", suggestion: "continue" },
  { word: "examination", suggestion: "examine" },
  { word: "investigation", suggestion: "investigate" },
  { word: "facilitation", suggestion: "facilitate" },
  { word: "notification", suggestion: "notify" },
  { word: "visualization", suggestion: "visualize" },
  { word: "demonstration", suggestion: "demonstrate" },
  { word: "transformation", suggestion: "transform" },
  { word: "simplification", suggestion: "simplify" },
  { word: "maximization", suggestion: "maximize" },
  { word: "minimization", suggestion: "minimize" },
  { word: "finalization", suggestion: "finalize" },
  { word: "prioritization", suggestion: "prioritize" },
  { word: "customization", suggestion: "customize" },
  { word: "generation", suggestion: "generate" },
  { word: "consumption", suggestion: "consume" },
  { word: "acquisition", suggestion: "acquire" },
  { word: "distribution", suggestion: "distribute" },
  { word: "accumulation", suggestion: "accumulate" },
  { word: "acceleration", suggestion: "accelerate" },
  { word: "collaboration", suggestion: "collaborate" },
  { word: "communication", suggestion: "communicate" },
  { word: "recommendation", suggestion: "recommend" },
  { word: "consideration", suggestion: "consider" },
  { word: "interpretation", suggestion: "interpret" },
  { word: "consolidation", suggestion: "consolidate" },
  { word: "validation", suggestion: "validate" },
  { word: "verification", suggestion: "verify" },
  { word: "integration", suggestion: "integrate" },
  { word: "migration", suggestion: "migrate" },
  { word: "allocation", suggestion: "allocate" },
  { word: "calculation", suggestion: "calculate" },
  { word: "delegation", suggestion: "delegate" },
  { word: "duplication", suggestion: "duplicate" },
  { word: "elimination", suggestion: "eliminate" },
  { word: "evaluation", suggestion: "evaluate" },
  { word: "formulation", suggestion: "formulate" },
  { word: "indication", suggestion: "indicate" },
  { word: "installation", suggestion: "install" },
  { word: "introduction", suggestion: "introduce" },
  { word: "manipulation", suggestion: "manipulate" },
  { word: "negotiation", suggestion: "negotiate" },
  { word: "observation", suggestion: "observe" },
  { word: "operation", suggestion: "operate" },
  { word: "preparation", suggestion: "prepare" },
  { word: "presentation", suggestion: "present" },
  { word: "preservation", suggestion: "preserve" },
  { word: "prevention", suggestion: "prevent" },
  { word: "production", suggestion: "produce" },
  { word: "protection", suggestion: "protect" },
  { word: "publication", suggestion: "publish" },
  { word: "regulation", suggestion: "regulate" },
  { word: "registration", suggestion: "register" },
  { word: "replication", suggestion: "replicate" },
  { word: "representation", suggestion: "represent" },
  { word: "resolution", suggestion: "resolve" },
  { word: "restoration", suggestion: "restore" },
  { word: "restriction", suggestion: "restrict" },
  { word: "separation", suggestion: "separate" },
  { word: "simulation", suggestion: "simulate" },
  { word: "stimulation", suggestion: "stimulate" },
  { word: "substitution", suggestion: "substitute" },
  { word: "termination", suggestion: "terminate" },
  { word: "translation", suggestion: "translate" },
  { word: "variation", suggestion: "vary" },
  { word: "violation", suggestion: "violate" },
  { word: "aggregation", suggestion: "aggregate" },
  { word: "annotation", suggestion: "annotate" },
  { word: "approximation", suggestion: "approximate" },
  { word: "centralization", suggestion: "centralize" },
  { word: "classification", suggestion: "classify" },
  { word: "compensation", suggestion: "compensate" },
  { word: "completion", suggestion: "complete" },
  { word: "compression", suggestion: "compress" },
  { word: "concatenation", suggestion: "concatenate" },
  { word: "confirmation", suggestion: "confirm" },
  { word: "connection", suggestion: "connect" },
  { word: "construction", suggestion: "construct" },
  { word: "conversion", suggestion: "convert" },
  { word: "coordination", suggestion: "coordinate" },
  { word: "creation", suggestion: "create" },
  { word: "decoration", suggestion: "decorate" },
  { word: "definition", suggestion: "define" },
  { word: "derivation", suggestion: "derive" },
  { word: "description", suggestion: "describe" },
  { word: "destruction", suggestion: "destroy" },
  { word: "detection", suggestion: "detect" },
  { word: "deviation", suggestion: "deviate" },
  { word: "differentiation", suggestion: "differentiate" },
  { word: "digitization", suggestion: "digitize" },
  { word: "escalation", suggestion: "escalate" },
  { word: "estimation", suggestion: "estimate" },
  { word: "execution", suggestion: "execute" },
  { word: "expansion", suggestion: "expand" },
  { word: "exploration", suggestion: "explore" },
  { word: "exportation", suggestion: "export" },
  { word: "extraction", suggestion: "extract" },
  { word: "fabrication", suggestion: "fabricate" },
  { word: "identification", suggestion: "identify" },
  { word: "illustration", suggestion: "illustrate" },
  { word: "importation", suggestion: "import" },
  { word: "improvisation", suggestion: "improvise" },
  { word: "incorporation", suggestion: "incorporate" },
  { word: "iteration", suggestion: "iterate" },
  { word: "justification", suggestion: "justify" },
  { word: "legalization", suggestion: "legalize" },
  { word: "modernization", suggestion: "modernize" },
  { word: "monetization", suggestion: "monetize" },
  { word: "normalization", suggestion: "normalize" },
  { word: "organization", suggestion: "organize" },
  { word: "origination", suggestion: "originate" },
  { word: "participation", suggestion: "participate" },
  { word: "personalization", suggestion: "personalize" },
  { word: "polarization", suggestion: "polarize" },
  { word: "privatization", suggestion: "privatize" },
  { word: "proliferation", suggestion: "proliferate" },
  { word: "rationalization", suggestion: "rationalize" },
  { word: "reconciliation", suggestion: "reconcile" },
  { word: "remediation", suggestion: "remediate" },
  { word: "renovation", suggestion: "renovate" },
  { word: "reorganization", suggestion: "reorganize" },
  { word: "serialization", suggestion: "serialize" },
  { word: "standardization", suggestion: "standardize" },
  { word: "synchronization", suggestion: "synchronize" },
  { word: "utilisation", suggestion: "use" },
  { word: "visualisation", suggestion: "visualize" },
  // -ment words
  { word: "improvement", suggestion: "improve" },
  { word: "development", suggestion: "develop" },
  { word: "achievement", suggestion: "achieve" },
  { word: "replacement", suggestion: "replace" },
  { word: "requirement", suggestion: "require" },
  { word: "measurement", suggestion: "measure" },
  { word: "assessment", suggestion: "assess" },
  { word: "deployment", suggestion: "deploy" },
  { word: "engagement", suggestion: "engage" },
  { word: "enhancement", suggestion: "enhance" },
  { word: "enforcement", suggestion: "enforce" },
  { word: "involvement", suggestion: "involve" },
  { word: "management", suggestion: "manage" },
  { word: "arrangement", suggestion: "arrange" },
  { word: "advancement", suggestion: "advance" },
  { word: "abandonment", suggestion: "abandon" },
  { word: "accomplishment", suggestion: "accomplish" },
  { word: "acknowledgement", suggestion: "acknowledge" },
  { word: "adjustment", suggestion: "adjust" },
  { word: "agreement", suggestion: "agree" },
  { word: "alignment", suggestion: "align" },
  { word: "amazement", suggestion: "amaze" },
  { word: "amusement", suggestion: "amuse" },
  { word: "announcement", suggestion: "announce" },
  { word: "attachment", suggestion: "attach" },
  { word: "attainment", suggestion: "attain" },
  { word: "bewilderment", suggestion: "bewilder" },
  { word: "commitment", suggestion: "commit" },
  { word: "containment", suggestion: "contain" },
  { word: "detachment", suggestion: "detach" },
  { word: "discouragement", suggestion: "discourage" },
  { word: "displacement", suggestion: "displace" },
  { word: "embodiment", suggestion: "embody" },
  { word: "empowerment", suggestion: "empower" },
  { word: "encouragement", suggestion: "encourage" },
  { word: "endangerment", suggestion: "endanger" },
  { word: "enrichment", suggestion: "enrich" },
  { word: "entanglement", suggestion: "entangle" },
  { word: "entertainment", suggestion: "entertain" },
  { word: "entitlement", suggestion: "entitle" },
  { word: "environment", suggestion: "surround" },
  { word: "equipment", suggestion: "equip" },
  { word: "excitement", suggestion: "excite" },
  { word: "fulfillment", suggestion: "fulfill" },
  { word: "imprisonment", suggestion: "imprison" },
  { word: "inducement", suggestion: "induce" },
  { word: "investment", suggestion: "invest" },
  { word: "judgment", suggestion: "judge" },
  { word: "mismanagement", suggestion: "mismanage" },
  { word: "postponement", suggestion: "postpone" },
  { word: "procurement", suggestion: "procure" },
  { word: "punishment", suggestion: "punish" },
  { word: "resentment", suggestion: "resent" },
  { word: "retirement", suggestion: "retire" },
  { word: "settlement", suggestion: "settle" },
  { word: "statement", suggestion: "state" },
  { word: "treatment", suggestion: "treat" },
  // -ence/-ance words
  { word: "acceptance", suggestion: "accept" },
  { word: "allowance", suggestion: "allow" },
  { word: "appearance", suggestion: "appear" },
  { word: "assistance", suggestion: "assist" },
  { word: "avoidance", suggestion: "avoid" },
  { word: "compliance", suggestion: "comply" },
  { word: "dependence", suggestion: "depend" },
  { word: "disappearance", suggestion: "disappear" },
  { word: "disturbance", suggestion: "disturb" },
  { word: "dominance", suggestion: "dominate" },
  { word: "emergence", suggestion: "emerge" },
  { word: "endurance", suggestion: "endure" },
  { word: "existence", suggestion: "exist" },
  { word: "governance", suggestion: "govern" },
  { word: "guidance", suggestion: "guide" },
  { word: "hindrance", suggestion: "hinder" },
  { word: "ignorance", suggestion: "ignore" },
  { word: "inheritance", suggestion: "inherit" },
  { word: "insistence", suggestion: "insist" },
  { word: "interference", suggestion: "interfere" },
  { word: "maintenance", suggestion: "maintain" },
  { word: "occurrence", suggestion: "occur" },
  { word: "performance", suggestion: "perform" },
  { word: "persistence", suggestion: "persist" },
  { word: "preference", suggestion: "prefer" },
  { word: "prevalence", suggestion: "prevail" },
  { word: "reference", suggestion: "refer" },
  { word: "reliance", suggestion: "rely" },
  { word: "reluctance", suggestion: "hesitate" },
  { word: "remembrance", suggestion: "remember" },
  { word: "resemblance", suggestion: "resemble" },
  { word: "resistance", suggestion: "resist" },
  { word: "tolerance", suggestion: "tolerate" },
  { word: "utterance", suggestion: "utter" },
  { word: "variance", suggestion: "vary" },
];

// Hedging phrases that weaken writing
export const hedgingPhrases: string[] = [
  // Personal uncertainty
  "I think", "I believe", "I feel", "I suppose", "I guess",
  "I imagine", "I assume", "I suspect", "I reckon",
  "I would say", "I would argue", "I would suggest",
  "I would think", "I would hope", "I would expect",
  "I tend to think", "I tend to believe",
  // Impersonal hedging
  "it seems", "it appears", "it would seem", "it would appear",
  "it could be said", "it might be said", "it may be said",
  "it could be argued", "it might be argued",
  "it is possible that", "it is likely that", "it is conceivable that",
  "it is worth noting", "it should be noted", "it must be noted",
  "it is interesting to note", "it goes without saying",
  "one could argue", "one might argue", "one might say",
  "one could say", "one would think", "one would expect",
  // Qualifying phrases
  "in my opinion", "in my view", "in my experience",
  "to my knowledge", "to my mind", "to my way of thinking",
  "from my perspective", "from my point of view",
  "as far as I know", "as far as I can tell",
  "as far as I am aware", "as far as I understand",
  "if I'm not mistaken", "if I recall correctly",
  "if my memory serves", "if I may say so",
  "to some extent", "to a certain degree", "to a certain extent",
  "to a large extent", "to a greater or lesser degree",
  "in some ways", "in some respects", "in a sense", "in a way",
  "more or less", "for the most part", "by and large",
  "on the whole", "all things considered",
  // Softening phrases
  "needless to say", "it stands to reason",
  "with all due respect", "if you will",
  "so to speak", "as it were", "in a manner of speaking",
  "at the end of the day", "when all is said and done",
  "having said that", "that being said", "that said",
  "be that as it may", "for what it's worth",
  // Tentative language
  "there is a chance that", "there is a possibility that",
  "there is reason to believe", "there is some evidence",
  "the evidence suggests", "this suggests that",
  "this seems to indicate", "this appears to show",
  "this would suggest", "this might indicate",
  "this could mean", "this may imply",
  "not entirely clear", "not fully understood",
  "remains to be seen", "time will tell",
];

// Filler adverbs (no overlap with allWeaselWords)
// Excluded: actually, almost, apparently, arguably, basically, certainly,
// clearly, commonly, comparatively, completely, conceivably, curiously,
// definitely, essentially, evidently, exceedingly, extremely, fairly,
// frequently, generally, hypothetically, importantly, just, largely,
// literally, marginally, maybe, mildly, moderately, mostly, nearly,
// notably, obviously, occasionally, oddly, often, ostensibly, peculiarly,
// perhaps, possibly, presumably, probably, purportedly, quite, rarely,
// rather, really, reasonably, relatively, remarkably, seemingly, seldom,
// significantly, simply, slightly, sometimes, somewhat, strangely,
// substantially, supposedly, surprisingly, theoretically, typically,
// undoubtedly, unquestionably, usually, virtually
export const fillerAdverbs: string[] = [
  "absolutely", "accordingly", "admittedly", "altogether",
  "assuredly", "categorically", "chronically", "collectively",
  "comparably", "compellingly", "conclusively", "consequently",
  "consistently", "constantly", "continually", "critically",
  "decidedly", "demonstrably", "desperately", "disproportionately",
  "drastically", "effectively", "effortlessly", "emphatically",
  "enormously", "entirely", "especially", "excitedly",
  "exclusively", "exponentially", "extraordinarily", "faithfully",
  "fortunately", "fundamentally", "genuinely", "globally",
  "gracefully", "greatly", "hastily", "historically",
  "honestly", "hopefully", "hugely", "ideally",
  "immensely", "immediately", "impossibly", "incidentally",
  "incredibly", "independently", "indisputably", "inevitably",
  "infinitely", "inherently", "insanely", "instantly",
  "irrefutably", "ironically", "markedly", "massively",
  "materially", "measurably", "mercifully", "merely",
  "miraculously", "monumentally", "naturally", "necessarily",
  "noticeably", "objectively", "obscurely", "overwhelmingly",
  "overly", "painfully", "paradoxically", "particularly",
  "perfectly", "permanently", "personally", "plainly",
  "plausibly", "positively", "practically", "precisely",
  "predictably", "predominantly", "primarily", "principally",
  "profoundly", "progressively", "promptly", "proportionally",
  "purely", "radically", "rapidly", "regrettably",
  "reliably", "remarkedly", "repeatedly", "reportedly",
  "respectively", "ridiculously", "routinely", "sadly",
  "seriously", "severely", "sharply", "singularly",
  "solely", "specifically", "spectacularly", "steadily",
  "strikingly", "strongly", "stubbornly", "sufficiently",
  "surely", "suspiciously", "technically", "thankfully",
  "thoroughly", "tirelessly", "totally", "tremendously",
  "truly", "unanimously", "unconditionally", "undeniably",
  "understandably", "unfortunately", "uniformly", "uniquely",
  "universally", "unnecessarily", "unreasonably", "utterly",
  "vastly", "vigorously", "wholly", "wildly",
];

// Common abbreviations that should not be treated as sentence boundaries
export const abbreviations = new Set([
  // Titles
  "mr", "mrs", "ms", "dr", "prof", "sr", "jr", "st",
  "rev", "hon", "sgt", "cpl", "pvt", "gen", "col",
  "lt", "cmdr", "adm", "capt", "maj",
  // Academic / professional
  "ph.d", "m.d", "b.a", "m.a", "b.s", "m.s", "j.d", "d.d.s",
  "esq", "cpa", "dvm",
  // Common abbreviations
  "e.g", "i.e", "etc", "vs", "approx", "dept", "est",
  "govt", "inc", "corp", "ltd", "no", "vol", "fig",
  "assn", "ave", "blvd", "bldg", "ct", "dist",
  "ed", "ft", "hwy", "mt", "natl", "pkg",
  "rd", "sq", "univ", "yr",
  // Months
  "jan", "feb", "mar", "apr", "jun", "jul",
  "aug", "sep", "sept", "oct", "nov", "dec",
  // Units
  "oz", "lb", "lbs", "kg", "km", "mi", "pt", "qt", "gal",
  "min", "sec", "hr", "hrs",
  // Other
  "al", "cf", "ref", "tel", "fax", "misc", "temp",
  "govt", "org", "co", "intl",
]);

// AI-tells vocabulary: words that appear 10x-200x more often in AI text than human text
// Sources: GPTZero corpus analysis, CMU PNAS study
export const aiTellsVocabulary: Array<{ word: string; reason: string }> = [
  // Tier 1: Extreme overuse (50x-200x)
  { word: 'delve', reason: '"delve" appears ~150x more in AI text than human text' },
  { word: 'tapestry', reason: '"tapestry" (metaphorical) is a strong AI vocabulary marker' },
  { word: 'multifaceted', reason: '"multifaceted" is heavily overrepresented in AI writing' },
  { word: 'commendable', reason: '"commendable" is a classic AI praise word' },
  { word: 'meticulous', reason: '"meticulous" appears far more often in AI than human text' },
  { word: 'intricate', reason: '"intricate" is disproportionately used by AI models' },
  // Tier 2: Strong overuse (20x-50x)
  { word: 'nuanced', reason: '"nuanced" is a frequent AI filler adjective' },
  { word: 'comprehensive', reason: '"comprehensive" is overused by AI as a generic intensifier' },
  { word: 'pivotal', reason: '"pivotal" is disproportionately favored by AI' },
  { word: 'holistic', reason: '"holistic" appears far more in AI text than human writing' },
  { word: 'groundbreaking', reason: '"groundbreaking" is AI hyperbole' },
  { word: 'transformative', reason: '"transformative" is a strong AI vocabulary signal' },
  { word: 'encompasses', reason: '"encompasses" is overrepresented in AI-generated text' },
  { word: 'embark', reason: '"embark" (especially "embark on a journey") is a known AI tell' },
  { word: 'fostering', reason: '"fostering" is used ~30x more by AI models' },
  { word: 'spearheading', reason: '"spearheading" is a classic AI action verb' },
  { word: 'underscores', reason: '"underscores" is overused by AI for emphasis' },
  { word: 'underpins', reason: '"underpins" is disproportionately AI-favored' },
  { word: 'leveraging', reason: '"leveraging" is AI-corporate jargon rarely used naturally' },
  { word: 'landscape', reason: '"landscape" (metaphorical) is a known AI tell' },
  { word: 'testament', reason: '"testament" is overused by AI ("a testament to...")' },
  { word: 'noteworthy', reason: '"noteworthy" is disproportionately AI-generated' },
  { word: 'invaluable', reason: '"invaluable" is overrepresented in AI text' },
  { word: 'elevate', reason: '"elevate" is a frequent AI verb' },
  // Tier 3: Moderate overuse (10x-20x)
  { word: 'robust', reason: '"robust" is AI jargon — humans rarely use it outside engineering' },
  { word: 'streamline', reason: '"streamline" is overrepresented in AI-generated content' },
  { word: 'crucial', reason: '"crucial" is overused by AI where "important" would do' },
  { word: 'realm', reason: '"realm" (metaphorical, "in the realm of") is AI-favored' },
  { word: 'paradigm', reason: '"paradigm" is overrepresented in AI text' },
  { word: 'myriad', reason: '"myriad" is disproportionately AI-generated' },
  { word: 'plethora', reason: '"plethora" is a known AI vocabulary marker' },
  { word: 'beacon', reason: '"beacon" (metaphorical) is AI-overused' },
  { word: 'bustling', reason: '"bustling" is overrepresented in AI descriptions' },
  { word: 'camaraderie', reason: '"camaraderie" appears ~150x more in ChatGPT text (CMU study)' },
  { word: 'resonate', reason: '"resonate" / "resonates" is disproportionately AI' },
  { word: 'bespoke', reason: '"bespoke" is overrepresented in AI writing' },
  { word: 'esteemed', reason: '"esteemed" is AI-formal language rarely used naturally' },
  { word: 'unparalleled', reason: '"unparalleled" is AI superlative overuse' },
  { word: 'harness', reason: '"harness" (as verb) is AI-overused' },
  { word: 'adept', reason: '"adept" is disproportionately AI-generated' },
  { word: 'aligns', reason: '"aligns" / "aligns with" is AI transition overuse' },
];

// AI-tells phrases: multi-word patterns that are strong AI indicators
export const aiTellsPhrases: Array<{ phrase: string; reason: string }> = [
  // Sycophantic / conversational openers
  { phrase: 'great question', reason: 'Sycophantic AI opener — humans rarely say this in writing' },
  { phrase: 'excellent question', reason: 'Sycophantic AI opener' },
  { phrase: 'glad you asked', reason: 'AI conversational filler' },
  // Hedging preambles
  { phrase: "it's important to note that", reason: 'AI hedging preamble — add the point directly' },
  { phrase: "it's worth noting that", reason: 'AI hedging filler' },
  { phrase: "it's worth mentioning that", reason: 'AI hedging filler — just mention it' },
  { phrase: 'it should be noted that', reason: 'AI passive hedge' },
  // Filler openers
  { phrase: "in today's fast-paced world", reason: 'AI cliche opener — 107x more in AI text than human' },
  { phrase: "in today's digital age", reason: 'AI cliche opener' },
  { phrase: "in today's rapidly evolving", reason: 'AI cliche opener variant' },
  { phrase: 'in the realm of', reason: 'AI filler phrase — 50x overrepresentation' },
  { phrase: 'in an era of', reason: 'AI scene-setting cliche' },
  { phrase: 'at its core', reason: 'AI emphasis filler — often adds nothing' },
  { phrase: 'at the end of the day', reason: 'AI cliche wrap-up phrase' },
  { phrase: 'when it comes to', reason: 'AI transition filler — overused as topic introducer' },
  // Overly formal transitions
  { phrase: 'furthermore,', reason: 'AI transition — "also" or "and" is more natural' },
  { phrase: 'moreover,', reason: 'AI transition overuse' },
  { phrase: 'additionally,', reason: 'AI transition overuse — "also" is more natural' },
  { phrase: 'consequently,', reason: 'AI transition — "so" is more natural in most contexts' },
  { phrase: 'in conclusion,', reason: 'AI structural cliche — rarely needed' },
  // "Let's" constructions
  { phrase: "let's dive in", reason: 'AI conversational filler' },
  { phrase: "let's explore", reason: 'AI conversational filler — just explore it' },
  { phrase: "let's delve", reason: 'AI filler combining two tells' },
  { phrase: "let's break this down", reason: 'AI structural filler' },
  { phrase: 'without further ado', reason: 'AI filler phrase before getting to the point' },
  // Superlative/emphasis
  { phrase: 'a testament to', reason: 'AI emphasis cliche' },
  { phrase: 'plays a crucial role', reason: 'AI emphasis cliche' },
  { phrase: "it's not just about", reason: 'AI negation-pivot opener' },
  // Wrap-up phrases
  { phrase: 'embrace the', reason: 'AI call-to-action cliche ("embrace the future")' },
  { phrase: 'navigate the complexities', reason: 'AI closing cliche' },
  { phrase: 'pave the way for', reason: 'AI forward-looking cliche' },
  { phrase: 'the possibilities are endless', reason: 'AI optimism cliche' },
  { phrase: 'only time will tell', reason: 'AI non-committal closing' },
];
